### ISSUE TITLE
回傳數字型態錯誤

### ISSUE THREAD

**Issue by henry11996** [RainrainWu/fugle-realtime-go#11]
"meta": {
      "isIndex": false,
      "nameZhTw": "台積電",
      "industryZhTw": "半導體業",
      "priceReference": 602, <-- 轉換是用 int
      "priceHighLimit": 662, <-- 轉換是用 int
      "priceLowLimit": 542, <-- 轉換是用 int
    },

當我用0056有小數點的數字會直接變成0
當我改成float後就正常了

**Comment by RainrainWu** [comment]
@henry11996 Hi, 感謝你回報 Issue!

我當初沒有測到小數點的代號所以沒注意到這問題
Fugle 官方文件的型別是寫 `number` 我一開始也有點困惑
但測了幾個股票代號沒問題我就不疑有他了 XD

處理小數點的數值考慮到精度問題我會傾向使用 Decimal Type
我順手也把其他在文件上型別是 `number` 的欄位也改成 Decimal 了
PR 發在 #12 那裡，如果有空的話可以幫忙過目一下嗎～

<img width="630" alt="截圖 2021-05-01 下午8 03 58" src="https://user-images.githubusercontent.com/26277801/116781874-60d1d200-aab8-11eb-8de7-79f33e02165f.png">
